# Generated by Django 3.0.4 on 2020-04-19 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reports', models.CharField(max_length=200)),
                ('team_lead', models.CharField(max_length=200)),
                ('no_of_hours', models.IntegerField(default=0)),
                ('today_progress', models.CharField(max_length=200)),
                ('today_documents', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('concerns', models.TextField(blank=True)),
                ('next_plan', models.CharField(max_length=200)),
                ('nextplan_documents', models.FileField(upload_to='documents/%Y/%m/%d/')),
            ],
        ),
    ]
